# Generated by Django 2.2 on 2023-02-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, choices=[('HB', 'Hobbit'), ('LOTR', 'Lord of the rings')], default='', max_length=36, null=True),
        ),
    ]
